// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjErVNA1acnFadMWq0YghoBim0XUsbGY',
    appId: '1:598983347227:web:82334af61a0884dbdbbcbe',
    messagingSenderId: '598983347227',
    projectId: 'e-checksheet-38849',
    authDomain: 'e-checksheet-38849.firebaseapp.com',
    storageBucket: 'e-checksheet-38849.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKVw56-1Vq84bMTijs6Hb6LFY6xcdqjYY',
    appId: '1:598983347227:android:43545d074a6f6ef5dbbcbe',
    messagingSenderId: '598983347227',
    projectId: 'e-checksheet-38849',
    storageBucket: 'e-checksheet-38849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSZXNACGim94rHSjGnsmmQxGgbWYneM28',
    appId: '1:598983347227:ios:1af4eec4d9651aafdbbcbe',
    messagingSenderId: '598983347227',
    projectId: 'e-checksheet-38849',
    storageBucket: 'e-checksheet-38849.firebasestorage.app',
    iosBundleId: 'com.example.eChecksheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSZXNACGim94rHSjGnsmmQxGgbWYneM28',
    appId: '1:598983347227:ios:1af4eec4d9651aafdbbcbe',
    messagingSenderId: '598983347227',
    projectId: 'e-checksheet-38849',
    storageBucket: 'e-checksheet-38849.firebasestorage.app',
    iosBundleId: 'com.example.eChecksheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZjErVNA1acnFadMWq0YghoBim0XUsbGY',
    appId: '1:598983347227:web:fca0cfbd20d29506dbbcbe',
    messagingSenderId: '598983347227',
    projectId: 'e-checksheet-38849',
    authDomain: 'e-checksheet-38849.firebaseapp.com',
    storageBucket: 'e-checksheet-38849.firebasestorage.app',
  );
}
